name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn ${{ env.MAVEN_CLI_OPTS }} test
        env:
          MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-reports
          path: target/surefire-reports/TEST-*.xml

  oop-exam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create exam directory
        run: mkdir -p target/exam

      - name: Generate checksums
        run: |
          sha256sum test/it/polito/po/test/* > target/exam/checks.txt
          sha256sum pom.xml .github/workflows/ci.yml >> target/exam/checks.txt

      - name: Archive exam artifacts
        uses: actions/upload-artifact@v3
        with:
          name: exam
          path: target/exam/*